<div class="col-sm-12 content" ng-app="myApp" ng-controller="formCtrl">
	<div class="col-sm-12 margin-md" style="background-color: #f1f1f1;">
		<h2 style="text-align:center;">Med Test</h4>
		<h4 style="text-align:center;">Welcome: {{admin.login}}</h4>

		<div class="col-sm-10" style="background-color: #f1f1f1;">
		</div>
		<div class="col-sm-2 mr-xs-5" style=" margin-bottom:15px;">
					<button class="btn btn-primary btn-s btn-block btn-success" ng-click="checkLoginAction()" ng-disabled="false" >Login</button>
					<button class="btn btn-primary btn-s btn-block btn-danger" ng-click="logoutAction()" ng-disabled="false" >Logout</button>
		</div>
	</div>
	<div class="col-sm-3 sidenav" style="overflow-y: auto;">
	<!---->
		<div class="col-sm-12" ng-repeat="user in allUsers">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<button class="btn btn-primary btn-success" data-toggle="modal" data-target="#editUser" ng-click="beforeEditUserAction(user)" ng-disabled="false" >Edit</button>
					<button class="btn btn-primary btn-danger" ng-click="deleteUserAction(user)" ng-disabled="false" >Delete</button>
				</div>
				<div class="panel-body">
					<table class="table table-striped">
						<tr>
							<td>Id</td>
							<td>{{user.id}}</td>
						</tr>
						<tr>
							<td>Firstname</td>
							<td>{{user.firstname}}</td>
						</tr>
						<tr>
							<td>Lastname</td>
							<td>{{user.lastname}}</td>
						</tr>
						<tr>
							<td>Phone</td>
							<td>{{user.phone}}</td>
						</tr>
						<tr>
							<td>Email</td>
							<td>{{user.email}}</td>
						</tr>
					</table>
				</div>
			</div>
		</div>
	<!---->
	</div>
	<div class="col-sm-9">
		<div class="col-sm-12 content">
			<div class="">
				<h2>Create user form</h2>
				<div class="panel panel-default">
					<div class="panel-body">
						<form>
							<div class="form-group {{erorr.firstname.erorrClass}}">
								<label for="firstname">Firstname:</label>
								<input type="text" class="form-control" id="firstname" placeholder="Enter firstname" name="Firstname"  ng-model="createUser.firstname">
								<span ng-show="erorr.firstname.erorrShow" >{{erorr.firstname.erorrText}}</span>
							</div>
							<div class="form-group {{erorr.lastname.erorrClass}}">
								<label for="lastname">Lastname:</label>
								<input type="text" class="form-control" id="lastname" placeholder="Enter lastname" name="lastname"  ng-model="createUser.lastname">
								<span ng-show="erorr.lastname.erorrShow" >{{erorr.lastname.erorrText}}</span>
							</div>
							<div class="form-group {{erorr.phone.erorrClass}}">
								<label for="phone">Phone:</label>
								<input type="text" class="form-control" id="phone" placeholder="Enter phone" name="phone"  ng-model="createUser.phone">
								<span ng-show="erorr.phone.erorrShow" >{{erorr.phone.erorrText}}</span>
							</div>
							<div class="form-group {{erorr.email.erorrClass}}">
								<label for="email">Email:</label>
								<input type="email" class="form-control" id="email" placeholder="Enter email" name="email"  ng-model="createUser.email">
								<span ng-show="erorr.email.erorrShow" >{{erorr.email.erorrText}}</span>
							</div>

							<button class="btn btn-primary btn-success" ng-click="createUserAction()" ng-disabled="showButtonPaused" >Add new user</button> 
						</form>

					</div>
				</div>
			</div>
		</div>
	</div>

	<!--editUser-->

	<!-- Modal -->
	<div class="modal fade" id="editUser" role="dialog">
		<div class="modal-dialog">
			<!-- Modal content-->
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">Edit exist user</h4>
				</div>
				<div class="modal-body">
				  <div class="panel panel-default">
						<div class="panel-body">
							<form>
								<div class="form-group {{erorrEdit.firstname.erorrClass}}">
									<label for="firstname">Firstname:</label>
									<input type="text" class="form-control" id="edit_firstname" placeholder="Enter firstname" name="Firstname"  ng-model="editUser.firstname">
									<span ng-show="erorrEdit.firstname.erorrShow" >{{erorrEdit.firstname.erorrText}}</span>
								</div>
								<div class="form-group {{erorrEdit.lastname.erorrClass}}">
									<label for="lastname">Lastname:</label>
									<input type="text" class="form-control" id="edit_lastname" placeholder="Enter lastname" name="lastname"  ng-model="editUser.lastname">
									<span ng-show="erorrEdit.lastname.erorrShow" >{{erorrEdit.lastname.erorrText}}</span>
								</div>
								<div class="form-group {{erorrEdit.phone.erorrClass}}">
									<label for="phone">Phone:</label>
									<input type="text" class="form-control" id="edit_phone" placeholder="Enter phone" name="phone"  ng-model="editUser.phone">
									<span ng-show="erorrEdit.phone.erorrShow" >{{erorrEdit.phone.erorrText}}</span>
								</div>
								<div class="form-group {{erorrEdit.email.erorrClass}}">
									<label for="email">Email:</label>
									<input type="email" class="form-control" id="edit_email" placeholder="Enter email" name="email"  ng-model="editUser.email">
									<span ng-show="erorrEdit.email.erorrShow" >{{erorrEdit.email.erorrText}}</span>
								</div>

								<button  class="btn btn-primary btn-success" ng-click="editUserAction()" ng-disabled="showButtonPaused" >edit this user</button> 
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!---->

	<!--Login-->
	
	 <!-- Modal -->
	<div class="modal fade" id="loginForm" role="dialog">
		<div class="modal-dialog">
		
		<!-- Modal content-->
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">login</h4>
			</div>
			<div class="modal-body">
			  <div class="panel panel-default">
					<div class="panel-body">
						<form>
							<div class="form-group">
								<label for="email">Login:</label>
								<input type="text" class="form-control" id="admin_login" placeholder="Enter login" name="login"  ng-model="admin.login">
							</div>
							<div class="form-group">
								<label for="pwd">Password:</label>
								<input type="password" class="form-control" id="admin_password" placeholder="Enter password" name="password" ng-model="admin.password">
							</div>

							<button  class="btn btn-primary btn-success" ng-click="loginAction()" ng-disabled="showButtonPaused" >Login</button> 
						</form>

					</div>
				</div>
			</div>

		</div>
		</div>
	</div>
	<!---->
</div>



<script>
let app = angular.module('myApp', []);
app.controller('formCtrl', function($scope, $http, $interval) {
	$scope.erorr={};
	$scope.erorrEdit={};
	$scope.allUsers=[];
	$scope.createUser={};
	$scope.editUser={};
	$scope.admin={};

	$scope.checkLoginAction = function() {
		$http({
			method : "GET",
			url : "/auth/check",
			headers: {"Content-Type": "application/json"},
		}).then(
			function mySucces(response){
				$scope.admin = response.data;
				$("#loginForm").modal("hide");
			},
			function myError(response){
				if (response.status == 401){
					$("#loginForm").modal("show");
				} else {
					alert("Something wrong with server.");
				}
			}
		);
	};

	$scope.loginAction = function() {
		$http({
			method : "POST",
			url : "/auth/login",
			headers: {"Content-Type": "application/json"},
			data: $scope.admin
		}).then(
			function mySucces(response){
				$scope.admin = response.data;
				$("#loginForm").modal("hide");
			},
			function myError(response){
				if (response.status == 401){
					alert("Wrong: login - password.");
				} else {
					alert("Something wrong with server.");
				}
			}
		);
	};

	$scope.logoutAction = function() {
		$http({
			method : "POST",
			url : "/auth/logout",
			headers: {"Content-Type": "application/json"}
		}).then(
			function mySucces(response){
				$("#loginForm").modal("show");
			},
			function myError(response){
				if (response.status == 401){
					$("#loginForm").modal("show");
				} else {
					alert("Something wrong with server.");
				}
			}
		);
	};

	$scope.createUserAction = function() {
		$http({
			method : "POST",
			url : "/api/user/create",
			headers: {'Content-Type': 'application/json'},
			data: $scope.createUser
		}).then(
			function mySucces(response){
				$scope.createUser = {};
				$scope.erorr={};
				$scope.allUsers.unshift(response.data)
				alert('You have added new user.');
			},
			function myError(response){
				if (response.status == 401){
					$("#loginForm").modal("show");
				} else if(response.status == 400) {
					$scope.erorr={};

					if (Object.keys(response.data).length > 0){
						for (var key in response.data){
							$scope.checkErorrs($scope.erorr, key, response.data[key]);
						}
					} else {
						alert("Something wrong. Code: " + response.status);
					}
				} else {
					alert("Something wrong. Code: " + response.status);
				}
			}
		);
	};

	$scope.beforeEditUserAction = function(user){
		$scope.editUser = user;
		$scope.erorrEdit = {};
		console.log($scope.editUser);
	};

	$scope.editUserAction = function(){
		let editUrl = "/api/user/edit/" + $scope.editUser.id;

		$http({
			method : "PATCH",
			url : editUrl,
			headers: {'Content-Type': 'application/json'},
			data: $scope.editUser
		}).then(
			function mySucces(response){
				$scope.editUser = {};
				$scope.erorrEdit={};
				alert('You have edited user.');
				$("#editUser").modal("hide");
			},
			function myError(response){
				if (response.status == 401){
					$("#loginForm").modal("show");
				} else if(response.status == 400) {
					$scope.erorrEdit={};

					if (Object.keys(response.data).length > 0){
						for (var key in response.data){
							$scope.checkErorrs($scope.erorrEdit, key, response.data[key]);
						}
					} else {
						alert("Something wrong. Code: " + response.status);
					}
				} else {
					alert("Something wrong. Code: " + response.status);
				}
			}
		);
	};

	$scope.deleteUserAction = function(user){
		let deleteUrl = "/api/user/delete/" + user.id;

		$http({
			method : "DELETE",
			url : deleteUrl,
			headers: {'Content-Type': 'application/json'}
		}).then(
			function mySucces(response){
				$scope.getAllUsersAction();
				alert('You have edited user.');
			},
			function myError(response){
				if (response.status == 401){
					$("#loginForm").modal("show");
				} else {
					alert("Something wrong. Code: " + response.status);
				}
			}
		);
	};

	$scope.getAllUsersAction = function() {
		$http({
			method : "GET",
			url : "api/users/get",
			headers: {'Content-Type': 'application/json'},
		}).then(
			function mySucces(response){
				$scope.allUsers = response.data;
			},
			function myError(response){
				if (response.status == 401){
					$("#loginForm").modal("show");
				} else if(response.status == 404){
					$scope.allUsers=[];
				} else {
					alert("Something wrong. Code: " + response.status);
				}
			}
		);
	};

	$scope.checkErorrs = function(obj, key, value){
		obj[key]={};
		obj[key].erorrClass="has-error";
		obj[key].erorrShow="true";

		if (value=="empty"){
			obj[key].erorrText="Can not be empty.";
		}else if(value=="notvalid"){
			obj[key].erorrText="Fild is not valid.";
		}else if(value=="exist"){
			obj[key].erorrClass="has-warning";
			obj[key].erorrText="Already exist.";
		}
	};

	$scope.checkLoginAction();
	$scope.getAllUsersAction();
	/*
		$interval( function(){ $scope.getAllUsersAction(); }, 3000);
	*/
});
</script>