  <div class="col-sm-12 content" ng-app="myApp" ng-controller="formCtrl">
	<div class="col-sm-12" style="background-color: #f1f1f1;">
		<h4 style="text-align:center;">AlterEgo TEST SITE 1</h4>
	</div>
    <div class="col-sm-3 sidenav" style="overflow-y: auto;">
      <!---->
	  <div class="col-sm-12" ng-repeat="x in showAll">
		  <div class="panel panel-primary">
			<div class="panel-heading"><button class="btn btn-primary btn-danger" data-toggle="modal" data-target="#editPerson" ng-click="beforeEditPerson(x)" ng-disabled="false" >Edit</button></div>
			<div class="panel-body">
				<table class="table table-striped">
					  <tr>
						<td>Login</td>
						<td>{{x.login}}</td>
					  </tr>
					   <tr>
						<td>Lastname</td>
						<td>{{x.lastname}}</td>
					  </tr>
					   <tr>
						<td>Name</td>
						<td>{{x.name}}</td>
					  </tr>
					   <tr>
						<td>Email</td>
						<td>{{x.email}}</td>
					  </tr>
					   <tr>
						<td>Password</td>
						<td>{{x.password}}</td>
					  </tr>
				</table>
			</div>
		  </div>
	  </div>
      <!---->
    </div>
    <div class="col-sm-9">
  		<div class="col-sm-12 content">
  			<div class="">
				<h2>Login form</h2>
				<div class="panel panel-default">
				
		
				
					<div class="panel-body">
						<form>
							<div class="form-group {{erorr.login.erorrClass}}">
								<label for="email">Login:</label>
								<input type="text" class="form-control" id="login" placeholder="Enter login" name="login"  ng-model="user.login">
								<span ng-show="erorr.login.erorrShow" >{{erorr.login.erorrText}}</span>
							</div>
							<div class="form-group {{erorr.lastname.erorrClass}}">
								<label for="email">lastname:</label>
								<input type="text" class="form-control" id="lastname" placeholder="Enter last name" name="lastname"  ng-model="user.lastname">
								<span ng-show="erorr.lastname.erorrShow" >{{erorr.lastname.erorrText}}</span>
							</div>
							<div class="form-group {{erorr.name.erorrClass}}">
								<label for="email">Name:</label>
								<input type="text" class="form-control" id="name" placeholder="Enter name" name="name"  ng-model="user.name">
								<span ng-show="erorr.name.erorrShow" >{{erorr.name.erorrText}}</span>
							</div>
							<div class="form-group {{erorr.email.erorrClass}}">
								<label for="email">Email:</label>
								<input type="email" class="form-control" id="email" placeholder="Enter email" name="email"  ng-model="user.email">
								<span ng-show="erorr.email.erorrShow" >{{erorr.email.erorrText}}</span>
							</div>
							<div class="form-group {{erorr.password.erorrClass}}">
								<label for="pwd">Password:</label>
								<input type="password" class="form-control" id="password" placeholder="Enter password" name="password" ng-model="user.password">
								<span ng-show="erorr.password.erorrShow" >{{erorr.password.erorrText}}</span>
							</div>
							<input type="hidden" id="token"  name="token"  value="<?php echo $token; ?>" ng-model="user.token">
				
							<!-- <button type="submit" class="btn btn-default"  ng-disabled="showButtonPaused" >Submit</button> -->
							<button  class="btn btn-primary btn-danger" ng-click="registerPersons()" ng-disabled="showButtonPaused" >Add new user</button> 
							<!-- <p>{{user}}</p> -->
						</form>

					</div>
				</div>
			</div>
  		</div>
    </div>
	
	
	<!--editPerson-->
	
	 <!-- Modal -->
	<div class="modal fade" id="editPerson" role="dialog">
		<div class="modal-dialog">
		
		  <!-- Modal content-->
		  <div class="modal-content">
			<div class="modal-header">
			  <button type="button" class="close" data-dismiss="modal">&times;</button>
			  <h4 class="modal-title">Edit exist user</h4>
			</div>
			<div class="modal-body">
			  <div class="panel panel-default">
					<div class="panel-body">
						<form>				
							<div class="form-group {{erorrEdit.login.erorrClass}}">
								<label for="email">Login:</label>
								<input type="text" class="form-control" id="edit_login" placeholder="Enter login" name="login"  ng-model="editUser.login">
								<span ng-show="erorrEdit.login.erorrShow" >{{erorrEdit.login.erorrText}}</span>
							</div>						
							<div class="form-group {{erorrEdit.lastname.erorrClass}}">
								<label for="email">lastname:</label>
								<input type="text" class="form-control" id="edit_lastname" placeholder="Enter last name" name="lastname"  ng-model="editUser.lastname">
								<span ng-show="erorrEdit.lastname.erorrShow" >{{erorrEdit.lastname.erorrText}}</span>
							</div>
							<div class="form-group  {{erorrEdit.name.erorrClass}}">
								<label for="email">Name:</label>
								<input type="text" class="form-control" id="edit_name" placeholder="Enter name" name="name"  ng-model="editUser.name">
								<span ng-show="erorrEdit.name.erorrShow" >{{erorrEdit.name.erorrText}}</span>
							</div>
							<div class="form-group {{erorrEdit.email.erorrClass}}">
								<label for="email">Email:</label>
								<input type="email" class="form-control" id="edit_email" placeholder="Enter email" name="email"  ng-model="editUser.email">
								<span ng-show="erorrEdit.email.erorrShow" >{{erorrEdit.email.erorrText}}</span>
							</div>							
							<div class="form-group {{erorrEdit.password.erorrClass}}">
								<label for="pwd">Password:</label>
								<input type="password" class="form-control" id="edit_password" placeholder="Enter password" name="password" ng-model="editUser.password">
								<span ng-show="erorrEdit.password.erorrShow" >{{erorrEdit.password.erorrText}}</span>
							</div>
							<input type="hidden" id="edit_token"  name="token"  value="<?php echo $token; ?>" ng-model="editUser.token">
							<input type="hidden" id="edit_id"  name="id" ng-model="editUser.id">

							<!-- <button type="submit" class="btn btn-default"  ng-disabled="showButtonPaused" >Submit</button> -->
							<button  class="btn btn-primary btn-danger" ng-click="editPerson()" ng-disabled="showButtonPaused" >edit this user</button> 
						</form>

					</div>
				</div>
			</div>
	
		  </div>
		  
		</div>
	</div>
	<!---->
    
  </div>



<script>
var app = angular.module('myApp', []);
app.controller('formCtrl', function($scope, $http, $interval) {
	$scope.erorr={};
	$scope.erorrEdit={};
	$scope.showAll=[{'name':'name'}];
	$scope.user={};
	$scope.editUser={};
	$scope.user.token=$scope.editUser.token='<?php echo $token; ?>';

	$scope.registerPersons = function() {
		//console.log($scope.user);
	    $http({
	       method : "POST",
	       url : "/site/registration",
		   headers: {
						'Content-Type': 'application/x-www-form-urlencoded',
						'Token': '<?php echo $token; ?>'
					},
		   data: $.param($scope.user)
	     }).then(function mySucces(response) {
			 console.log(response.data);
			 $scope.erorr={};
			 if (Object.keys(response.data.data).length>0){
				 for (var key in response.data.data){
					 $scope.checkErorrs($scope.erorr,key,response.data.data[key]);
				 }
			 }else{
				alert('New user is added');
			 }		 
			 
	       }, function myError(response) {
			 console.log(response.data);
	     });
	}
	$scope.checkErorrs= function(obj,key,value){
		obj[key]={};
		obj[key].erorrClass="has-error";
		obj[key].erorrShow="true";
		if (value=="empty"){
			obj[key].erorrText="Can not be empty.";
		}else if(value=="notvalid"){
			obj[key].erorrText="Fild is not valid.";
		}else if(value=="exist"){
			obj[key].erorrClass="has-warning";
			obj[key].erorrText="Already exist.";
		}
		
		
	}
	$scope.beforeEditPerson=function(x){
		$scope.editUser=x;
		$scope.erorrEdit={};
		console.log($scope.editUser);
	}
	$scope.editPerson=function(){
		 $http({
	       method : "POST",
	       url : "/site/edit",
		   headers: {'Content-Type': 'application/x-www-form-urlencoded'},
		   data: $.param($scope.editUser)
	     }).then(function mySucces(response) {	 
			 console.log(response.data);
			 $scope.erorr={};
			 if (Object.keys(response.data.data).length>0){
				 for (var key in response.data.data){
					 $scope.checkErorrs($scope.erorrEdit,key,response.data.data[key]);
				 }
			 }else{
				alert('User has been edited');
			 }		 
	       }, function myError(response) {
			 console.log(response.data);
	     });
	}
	$scope.callTimeUpdate=function(){
		 $http({
	       method : "POST",
	       url : "/site/showall",
		   headers: {'Content-Type': 'application/x-www-form-urlencoded'},
		   data: $.param({})
	     }).then(function mySucces(response) {
	         $scope.showAll=response.data;
			 //console.log(response.data);
	       }, function myError(response) {
			 //console.log(response.data);
	     });
	}
	$scope.callTimeUpdate();
	$interval( function(){ $scope.callTimeUpdate(); }, 3000);

});
</script>