<div class="container" ng-app="myApp" ng-controller="formCtrl">
	<h2>Login form</h2>
	<div class="panel panel-default">
	
		<div class="panel-body">
		
			<form action="/site/login">
				<div class="form-group">
					<label for="email">Login:</label>
					<input type="text" class="form-control" id="login" placeholder="Enter login" name="login"  ng-model="user.login">
				</div>
				<div class="form-group">
					<label for="email">Login:</label>
					<input type="text" class="form-control" id="lastname" placeholder="Enter last name" name="lastname"  ng-model="user.lastname">
				</div>
				<div class="form-group">
					<label for="email">Login:</label>
					<input type="text" class="form-control" id="name" placeholder="Enter name" name="name"  ng-model="user.name">
				</div>
				<div class="form-group">
					<label for="email">Email:</label>
					<input type="email" class="form-control" id="email" placeholder="Enter email" name="email"  ng-model="user.email">
				</div>
				<div class="form-group">
					<label for="pwd">Password:</label>
					<input type="password" class="form-control" id="password" placeholder="Enter password" name="password" ng-model="user.password">
				</div>
				<input type="hidden" class="form-control" id="password" placeholder="Enter password" name="password" ng-model="formData.token">
	
				<!-- <button type="submit" class="btn btn-default"  ng-disabled="showButtonPaused" >Submit</button> -->
				<button type="button" class="btn btn-primary btn-danger" ng-click="ExitFromCalls()" ng-disabled="showButtonPaused" >Завершити</button> 
				<p>{{user}}</p>
			</form>

		</div>
	</div>
</div>
<script>
var app = angular.module('myApp', []);
app.controller('formCtrl', function($scope, $http) {
	$scope.user;

	$scope.ExitFromCalls = function() {
		console.log($scope.user);
	   //  $http({
	   //     method : "POST",
	   //     url : "http://usersidetest.chv.ua/oper/operpage_statistik.php?operation",
		  //  headers: {'Content-Type': 'application/x-www-form-urlencoded'},
		  //  data: $.param({code_operation: "0"})
	   //   }).then(function mySucces(response) {
	   //       //$scope.myWelcome = response.data;
			 // window.location=window.location.href;
			 // console.log(response.data);
	   //     }, function myError(response) {
	   //       //$scope.myWelcome = response.statusText;
			 // console.log(response.data);
	   //   });
	}


});
</script>